### ISSUE TITLE
tstorage + gRPC = tstorage-server

### ISSUE THREAD

**Issue by bartmika** [nakabonne/tstorage#19]
Hello @nakabonne,

I saw your post about `tstorage` on HackerNews and I spent some time looking through the source code - and I love the project.

The challenge I have is I want to access `tstorage` by many applications simultaneously; as a result, I spent some time writing a `gRPC` service definition overtop of `tstorage` to turn it into a server application. I've created the repo [tstorage-server](https://github.com/bartmika/tstorage-server).

Have a look and feel free to use any bit of the code if you like. If not, no worries! Just wanted to say thanks again for your great work! 

Take care,
-Bart

**Comment by nakabonne** [comment]
Hi @bartmika, glad to hear that you're interested in this project and making an awesome project using `tstorage`. Actually I'm thinking about building a new TSDB with `tstorage`. Your `tstorage-server` will be definitely helpful for writing the transport layer. Thank you for letting me know!

BTW, feel free to open a PR to add your project that uses `tstorage` to the [Used By](https://github.com/nakabonne/tstorage/blob/main/README.md#used-by) section in the README if you don't mind.

**Comment by bartmika** [comment]
My pleasure @nakabonne. PR #24 created.

Wonderful to hear about the new TSDB in the works. I've created a blog post you can use to help you with the transport layer as well:

http://localhost:1313/post/2021/how-to-build-a-grpc-server-over-tstorage-to-create-tstorage-server/

Have a good one!

**Comment by nakabonne** [comment]
@bartmika I skimmed this post but plan to read it thoroughly later. Looks interesting to read!

**Comment by nakabonne** [comment]
@bartmika For now, I'm going to close this issue but feel free to comment whenever your project updates ;)

**Comment by nakabonne** [comment]
(I've just shared on Twitter as it's really interesting to read: https://twitter.com/nakabonne/status/1414406004209446913)
