### ISSUE TITLE
Can I ask a question? why not lock in here.  See the link below

### ISSUE THREAD

**Issue by keroro6** [nakabonne/tstorage#26]
https://github.com/nakabonne/tstorage/blob/832a3826434cb92acec0b7d3893cd7bf75c22c7e/partition_list.go#L77-L79

**Comment by nakabonne** [comment]
Hi @keroro6, thank you for your interest.

I would say we don't have to lock there at all. You can check it by writing a tiny test code like:

```go
func TestInsertRows(t *testing.T) {
	node := &partitionNode{
		val: &fakePartition{
			minT: 1,
		},
	}
	list := &partitionListImpl{
		numPartitions: 1,
		head:          node,
		tail:          node,
	}
	for i := 0; i < 10000; i++ {
		go list.insert(newMemoryPartition(nil, 0, ""))
	}
}
```

You can see any data race doesn't occur.

```
$ go test -race -v -run=TestInsertRows
=== RUN   TestInsertRows
--- PASS: TestInsertRows (0.26s)
PASS
ok      github.com/nakabonne/tstorage   0.550s
```

I'm opening to any questions.

**Comment by keroro6** [comment]
Thanks for your reply. I will try. I'm interest to the project really

**Comment by nakabonne** [comment]
Glad to hear that. Ask me anything.

**Comment by nakabonne** [comment]
Let me close this. Feel free to re-open if you come up with an additional question.
