### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by gedw99** [nakabonne/tstorage#29]
how about adding an examples folder ?

the readme has gists or bits but it would be easier to grok on this with examples.

**Comment by gedw99** [comment]
closing. found them in other repo. sorry

**Comment by nakabonne** [comment]
@gedw99 Hey, thank you for your interest. Could you tell me where are those repositories? It means [these repos](https://github.com/nakabonne/tstorage/network/dependents?package_id=UGFja2FnZS0yMzAzMTk5ODg1)?

Also, you can refer to [storage_examples_test.go](https://github.com/nakabonne/tstorage/blob/main/storage_examples_test.go) to see how to use this package.
