### ISSUE TITLE
Missing meta.json file

### ISSUE THREAD

**Issue by weeco** [nakabonne/tstorage#43]
When I abruptly stop the application it apparently does not necessarily write a meta.json file into the disk directories. On startup a log message like this will pop up then:

```
failed to open disk partition for config\\tsdb-data\\xy\\p-1635758430-1635769231: failed to read metadata: open config\\tsdb-data\\xy\\p-1635758430-1635769231\\meta.json: The system cannot find the file specified."
```

I'm unsure when the meta.json file is supposed to be written, hence I can't tell whether it's dependent on the fact that I abruptly stop the application or not. It's not easily testable for me because it takes some time until it writes these files I think? Let me know if I can provide further details, has happened a couple times already.

**Comment by nakabonne** [comment]
Thank you for reporting. You're quite right. I fixed to ignore those invalid partitions when starting because they can be recovered by WAL: [v0.3.4](https://github.com/nakabonne/tstorage/releases/tag/v0.3.4)
