### ISSUE TITLE
Support WAL to offer durability guarantees

### ISSUE THREAD

**Issue by nakabonne** [nakabonne/tstorage#5]
A write-ahead log is a required capability to provide durability guarantees. 

https://github.com/nakabonne/tstorage/blob/2ed7de6461aa61704ea8be0eaba2369bba0831b5/file_wal.go#L18-L21

**Comment by nakabonne** [comment]
@rugwirobaker Thank you for your interest 😄

**Comment by gedw99** [comment]
The project looks promising.

with a wall of in place it might make it easy to also do cdc and Ende support many storage servers for real time redundancy .

this golang storage system offer these types of guarantees.

https://github.com/kelindar/column

some of it is useful reading I suspect

**Comment by nakabonne** [comment]
@gedw99 Thank you for sharing the useful resource. Let me have a look it later 😄
