### ISSUE TITLE
inclusive end in Select

### ISSUE THREAD

**Issue by hazge** [nakabonne/tstorage#53]
During **Select** in this code  using >= instead of > making **end** inclusive which contradict with documentation for **Select**
```go
if end >= maxTimestamp {
	endIdx = int(size)
} else {
	// Use binary search because points are in-order.
	endIdx = sort.Search(int(size), func(i int) bool {
		return m.points[i].Timestamp >= end
	})
}
```

**Comment by nakabonne** [comment]
This is fixed by https://github.com/nakabonne/tstorage/pull/54
